[package]
name = "stormwind"
version = "0.1.0"
edition = "2021"

[dependencies]
home = "0.5.9"
reqwest = { version = "0.12.7", features = ["blocking","json"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
